<?php

namespace Vodroche\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends EntityRepository
{

	public function findByCategorieAndRegion($categorie, $region){

		$qb = $this->createQueryBuilder('v');

		$query = $qb->select('v')
                ->where(':categorie MEMBER OF v.categorie AND :region MEMBER OF v.region')
                ->setParameter('categorie', $categorie)
                ->setParameter('region', $region)
                ->getQuery();
 
    	return $query->getResult();
	}


}
